
###
POST http://localhost:4000/api/productos
Content-Type: application/json

{
    "nombre": "pizzaprueba2",
    "categoria": " Española",
    "precio": 40
    
    
}

###

GET http://localhost:4000/api/productos


###

PUT http://localhost:4000/api/productos/656e3676e91db881744f6d53
Content-Type: application/json

{

  "nombre": "pasta",
  "categoria": "Italiana",
  "precio": 100

}


###

GET http://localhost:4000/api/productos/656e362de91db881744f6d51

###

DELETE http://localhost:4000/api/productos/65775c49246c0cc50cd6ff9f

###

POST http://localhost:4000/api/usuarios
Content-Type: application/json

{
    "nombre": "Raul",
    "email": " Raul@gmail.com",
    "password": "1234",
    "direccion":"c/aslda",
    "tipo":true
}